 ## Введение

Много примеров есть в ноутбуке Python + numpy intro.ipynb


Можно открыть его рядом и смотреть

In [4]:
# Импортирую модуль для работы с массивами в питоне. Теперь ко всем функциям доступным в модуле numpy можно обращаться
# через np.*function_name*
import numpy as np

In [5]:
#Например так можно создать массив (array) из четырех нулей
zeros = np.zeros(4)
print(zeros)

[0. 0. 0. 0.]


In [10]:
#С ним можно делать всякое
print(zeros + 1)
print( (zeros + 1) * 2)

#доступ к элементам как в списке
print(zeros[2:3])

[1. 1. 1. 1.]
[2. 2. 2. 2.]
[0.]


In [12]:
#Двумерные массивы
zeros_2d = np.zeros((3,4))
zeros_2d
print(zeros_2d)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
#обращение к разным индексам через запятую
zeros_2d[1,2] = 239
zeros_2d

In [ ]:
#куски тоже можно так вырезать
zeros_2d[1:, 2:]

В numpy еще куча всего, это основной наш инструмент, я буду писать комментарии везде, где использую какие-то функции оттуда. 

Документация легко гуглится, введение на английском можно почитать тут
https://docs.scipy.org/doc/numpy/user/quickstart.html

## Освоимся немного с ноутбуком

In [ ]:
l = [x for x in range(5)]
l

Напишите функцию, которая вернет четные элементы списка l


In [ ]:
def get_even(some_list):
    *YOUR CODE HERE*
    return

In [ ]:
print(get_even(l))

Напишите функцию, которая вернет список из квадратов элементов списка l и проверьте, что работает


Напишите функцию, которая возвращает диагональные элементы квадратного двумерного массива

In [ ]:
#функцией np.arange(16) я создаю массив от 0 до 15 (поведение почти как у питоновской range, только возвращает уже массив)
#у каждого массива есть метод (фукнкция действующая на него самого) reshape, который меняет его форму. 
#т.е. после np.arange был массив [0,1,2....15] и у него была форма 1 на 16, а потом я сделал reshape((4,4))
#массив стал квадратным, формы (4,4)
square_matrix = np.arange(16).reshape((4,4))
square_matrix

In [ ]:
def get_diagonal(some_array):
    
    *YOUR CODE HERE*
    
    return 

In [ ]:
get_diagonal(square_matrix)

## Датасет

В эту часть кода можно сильно не вникать, расскажу потом на занятии. Здесь я создаю датасет и подготавливаю функцию чтобы его напечатать

In [ ]:
#Импортирую библиотеку для генерации линейных датасетов
from sklearn.datasets import make_regression

#библиотека для графиков
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
#Генерирую случайный датасет с шумом
X, y = make_regression(n_samples=100, n_features=1, noise = 30, random_state=239)


In [ ]:
#Так выглдит датасет
plt.scatter(X, y)

In [ ]:
# функция чтобы строить красивый график
def plot_with_estimated_line(X, y, theta):
    if X.shape[1] == 1:
        plt.scatter(X, y)
    else:
        plt.scatter(X[:, 0], y)

    line_x = np.array([min(X[:, 0]), max(X[:, 0])])
    line_y = np.array([element * theta[0] + theta[1] for element in line_x])

    plt.plot(line_x, line_y, c = 'r')

## Линейная регрессия

Ниже три функции и цикл, куда надо вписать свой код чтобы все заработало

In [ ]:
#Задаем произвольные коэффициенты нашей прямой
theta = np.random.random(2)
print(theta)

In [ ]:
#Так выглядит датасет c нынешней прямой
plot_with_estimated_line(X, y, theta)

In [ ]:
#Приклеиваю к X столбец единиц справа с помощью np.hstack - функции склеивающей массивы в горизонтальном направлении.
X = np.hstack((X, np.ones_like(X)))

In [ ]:
# Функция для подсчета ошибки при данном theta. В лекциях назывется I.
def calculate_loss(X, y, theta):
    loss = *YOUR CODE HERE*
    return loss

In [ ]:
#функция считающая производные theta. Формулы есть в слайдах 
def calculate_gradients(X, y, theta):
    theta_gradients = np.zeros_like(theta)
    
    theta_gradients = *YOUR CODE HERE*
    
    return theta_gradients

In [ ]:
#Один шаг градиентного спуска
def make_gradient_step(theta, theta_gradients, alpha):
    theta =  *YOUR CODE HERE*
    
    return theta

In [ ]:
#Собственно сам градиентный спуск

alpha = 0.001
start_loss = calculate_loss(X, y, theta)

while *YOUR CODE HERE*:
    theta_gradients = calculate_gradients(X, y, theta)
    theta = make_gradient_step(theta, theta_gradients, alpha)
    
    *YOUR CODE HERE*
    
end_loss = calculate_loss(X, y, theta)

In [ ]:
#Проверяем, что получилось
plot_with_estimated_line(X, y, theta)

In [ ]:
#Смотрим как поменялась ошибка
print("Ошибка после случайной инициализации: ", start_loss)
print("Ошибка после градиентного спуска: ", end_loss)

## Для дальнейшей творческой работы

Можно реализовать все тоже самое в многомерном случае

Можно заимплементить стохастический градиентный спуск и сравнить время работы\кол-во шагов с обычным градиентным спуском. Это будет не очень репрезентативно в одномерном случае, но тем не меннее. 